Update build-apk.yaml

diff --git a/.github/workflows/build-apk.yaml b/.github/workflows/build-apk.yaml
--- a/.github/workflows/build-apk.yaml
+++ b/.github/workflows/build-apk.yaml
@@ -46,11 +46,25 @@ jobs:
           FOLDER_NAME="${REPO_NAME}(${AUTHOR_NAME})"
           mkdir -p "$FOLDER_NAME"
           echo "$REPO_URL" > "$FOLDER_NAME/github.txt"
-          mv ./**/*.apk "$FOLDER_NAME/"
+
+      - name: Find APK files
+        id: find_apk
+        run: |
+          APK_FILES=$(find . -name '*.apk')
+          if [ -z "$APK_FILES" ]; then
+            echo "::error::No APK files found."
+            exit 1
+          fi
+          echo "::set-output name=apk_path::$APK_FILES"
+
+      - name: Move APK files
+        if: steps.find_apk.outputs.apk_path
+        run: |
+          mv ${{ steps.find_apk.outputs.apk_path }} "$FOLDER_NAME/"
 
       - name: Upload the APK artifact with 1 day retention
         uses: actions/upload-artifact@v3
         with:
-          path: ./*(*)
+          path: ${{ env.FOLDER_NAME }}
           name: ${{ env.FOLDER_NAME }}
           retention-days: 1
